### ISSUE TITLE
Why cu3(0,0,a) doesn't match with cu1(a) ?

### ISSUE THREAD

**Issue by Kuma-quant** [Blueqat/Blueqat#109]
**Why cu3(0,0,a) doesn't match with cu1(a) ?**
Even if I ignore the global phase, these matrices seem different.
I have attached a simple code to check it.

*Enviroment: Google Colab.*

**Get a matrix expression of cu1(a)**
```
circ_test = Circuit(2)
circ_test.cu1(math.pi/4)[0,1]
Matrix = circ_test.to_unitary()
print(Matrix)
```
It Returns,
`Matrix([[exp(-I*pi/16), 0, 0, 0], [0, exp(-I*pi/16), 0, 0], [0, 0, exp(-I*pi/16), 0], [0, 0, 0, exp(3*I*pi/16)]])`

**Get a matrix expression of cu3(0,0,a)**

```
circ_test = Circuit(2)
circ_test.cu3(0,0,math.pi/4)[0,1]
Matrix = circ_test.to_unitary()
print(Matrix)
```
It Returns,
`Matrix([[1, 0, 0, 0], [0, exp(-I*pi/8), 0, 0], [0, 0, 1, 0], [0, 0, 0, exp(I*pi/8)]])`

Even if I ignore the global phase, these matrices seem different.
Is it expected behavior?

---
On the other hand, non-controlled version of these, namely,  u3(0,0,a) and u1(a) , are same.
It is expected behavior.

**Get a matrix expression of u1(a)**
```
circ_test = Circuit(1)
circ_test.u1(math.pi/4)[0]
Matrix = circ_test.to_unitary()
print(Matrix)
```

`Matrix([[exp(-I*pi/8), 0], [0, exp(I*pi/8)]])`

**Get a matrix expression of u3(0,0,a)**

```
circ_test = Circuit(1)
circ_test.u3(0,0,math.pi/4)[0]
Matrix = circ_test.to_unitary()
print(Matrix)
```

`Matrix([[exp(-I*pi/8), 0], [0, exp(I*pi/8)]])`

**Comment by Kuma-quant** [comment]
Blueqat source code is,

```    
def fallback(self, n_qubits):
        return self._make_fallback_for_control_target_iter(
            n_qubits, lambda c, t: [
                U1Gate(t, (self.lambd - self.phi) / 2),
                CXGate((c, t)),
                U3Gate(t, -self.theta / 2, 0, -(self.phi + self.lambd) / 2),
                CXGate((c, t)),
                U3Gate(t, self.theta / 2, self.phi, 0),
            ])

```

According to qiskit implementation of cu3 [1], it should be fixed as follows,

```    
def fallback(self, n_qubits):
        return self._make_fallback_for_control_target_iter(
            n_qubits, lambda c, t: [
                U1Gate(c, (self.lambd + self.phi) / 2),
                U1Gate(t, (self.lambd - self.phi) / 2),
                CXGate((c, t)),
                U3Gate(t, -self.theta / 2, 0, -(self.phi + self.lambd) / 2),
                CXGate((c, t)),
                U3Gate(t, self.theta / 2, self.phi, 0),
            ])

```

Sorry if my suggestion is wrong....

Ref.
[1] https://qiskit.org/documentation/locale/ja/_modules/qiskit/extensions/standard/cu3.html

**Comment by gyu-don** [comment]
Thank you for reporting. It had been actual behaviour of Qiskit but modified in 2019 Nov.
https://github.com/Qiskit/qiskit-terra/commit/5b89b4c1cb49bedd54006f320279f724e8592b71

We will modify Blueqat as same as Qiskit behaviour.

**Comment by Kuma-quant** [comment]
Thanks for your reply,
Got it !

**Comment by gyu-don** [comment]
We removed cu3 and cu1 gates rather than modified to qiskit's behaviour. (#120)
New u/cu gates have additional parameter for the global phase of U(2) matrix, its specifications and behaviour is very clear.
